### ISSUE TITLE
Undefined symbols _AVPPlayerGetNaturalSize

### ISSUE THREAD

**Issue by tylkomat** [RenderHeads/UnityPlugin-AVProVideo#342]
**Describe the bug**
App does not compile for iOS any more after update to 1.10.3. I was compiling on Friday with an older version and then it was working. The same error also happens for armv7.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.10f1
 - AVPro Video version: 1.10.3
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
Undefined symbols for architecture arm64:
  "_AVPPlayerGetNaturalSize", referenced from:
      _OSXMediaPlayer_AVPPlayerGetNaturalSize_m2470D3B8815E8A6BF2AE817C8D4273839D3171BD in Assembly-CSharp5.o
      _OSXMediaPlayer_Update_mBE8C478DCE5A6568064E6DB59D073444259D06C6 in Assembly-CSharp5.o
     (maybe you meant: _OSXMediaPlayer_AVPPlayerGetNaturalSize_m2470D3B8815E8A6BF2AE817C8D4273839D3171BD)
ld: symbol(s) not found for architecture arm64

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
I just did a quick test of the package from the Asset Store and everything worked fine.
It looks like something went wrong with the upgrade process. Either the plugins didn't get upgraded in Unity or they failed to copy over correctly into your Xcode project.

**Comment by AndrewRH** [comment]
Hi @tylkomat did the suggested fix resolve the issue for you?

If we do not here back this issue will be closed automatically.

Thanks,
