### ISSUE TITLE
iOS project with AVPro 1.11.7 can not be built in Xcode 14

### ISSUE THREAD

**Issue by coderDove** [RenderHeads/UnityPlugin-AVProVideo#1605]
**Describe the issue**
I am trying to build an iOS project with Unity and AVPro 1.11.7 plugin and it always fails with undefined symbols error:

```
Undefined symbols for architecture arm64:
  "_MTLTextureDescriptorClass", referenced from:
      -[PVRTexture(Metal) metalTextureWithDevice:linear:] in libAVProVideoiOS.a(PVRTexture.o)
ld: symbol(s) not found for architecture arm64
```
This issue happens when I am trying to build even a test Unity project that contains an empty scene and only an AVPro plugin added. I have an existed big project that uses AVPro 1.11.7 so migrating to AVPro 2 will be a pretty big problem.

The question is if it is possible to resolve this issue and build a Unity project with AVPro 1.11.7 in latest Xcode? 

Thank you

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.1f1
 - AVPro Video version: AVPro 1.11.7 Trial 
 - Operating system version: macOS Venture 13.4.1

**To Reproduce**
1. Create a new Unity 3D project for mobile and add AVPro plugin
2. Configure iOS build in Unity and build a project
3. Try to build generated project in Xcode

**Logs**

```
Undefined symbols for architecture arm64:
  "_MTLTextureDescriptorClass", referenced from:
      -[PVRTexture(Metal) metalTextureWithDevice:linear:] in libAVProVideoiOS.a(PVRTexture.o)
ld: symbol(s) not found for architecture arm64
```

**Comment by Chris-RH** [comment]
Hi @coderDove,

Please note: 
AVPro Video version 1.11.7 was released on 13 November 2020.  
Xcode 14.0 was released on 12 Sep 2022
AVPro Video version 1 is depreciated and will therefore no longer be receiving any updates.  I'm not sure if there are any changes that you could make that will make it work.  I believe we had to change a few things for version 2 to work with xcode 14.
Our mac/iOS dev is away on annual leave at the moment. I can put the question to him, but we will be unable to test anything until he gets back.

**Comment by MorrisRH** [comment]
This is not an issue with Xcode, unfortunately that symbol is no longer present as part of the built iOS project with Unity 2022 hence the plugin failing to link.
Projects using AVPro Video 1.11.7 will build with Unity versions 2019.4.40f1 through 2021.3.27f1 so I would suggest trying to use the LTS version of 2021 for now.

**Comment by Chris-RH** [comment]
Hi @coderDove, 
Would you be able to the pdf of your invoice from the Unity Asset Store please.  Preferably from the email address in the pdf. Please send to unitysupport@renderheads.com

**Comment by coderDove** [comment]
hey @MorrisRH 
thanks for the reply! thanks for the suggestion. Yes, it worked fine with Unity 2019, and as soon as we migrated to Unity 2022 fully for project purposes the built started failing. I understand that AVPro 1.11.7 is deprecated but maybe there is a chance that some patch can be available for AVPro 1.11.7 + Unity 2022 or any unofficial or unstable branch or release is present with Unity 2022 support?

hey @Chris-RH 
yes, we have an invoice for the purchased AVPro version. Will forward it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) linking this issue

Thanks!

**Comment by Chris-RH** [comment]
We can look into providing a fix for it when @MorrisRH is back from leave.

**Comment by coderDove** [comment]
@Chris-RH that will be amazing! thanks a lot for it, really appreciate it!
We will forward an invoice later today to prove that we are an actual user of paid version of AVPro.

P.S. May I ask when this can happen? Definitely no rush and I understand that it can be not the highest priority for you when @MorrisRH is back, but may be you can mention when approximately this fix can be taken into development so we can plan some activities and our side as well.

Thank you again!

**Comment by MorrisRH** [comment]
Closing as this issue is being resolved privately

**Comment by szapata-moffitt** [comment]
Hi! Which was the solution? I'm currently facing the same issue, thanks in advance!

**Comment by MorrisRH** [comment]
Hey @szapata-moffitt, we'll need to provide you with the latest version. Send an email to unitysupport@renderheads.com with your proof of purchase (the invoice pdf from Unity) and we'll see what we can do.

**Comment by ToolBar1024** [comment]
Hello ! I meet same issue, We use the v1.11.7 on unity3d 2022.3.17 ,and we hope keep the old version of avpro. 
But we can't found our invoice no, we can purchase the asset again. can we use  this link https://assetstore.unity.com/packages/tools/video/avpro-video-v3-core-edition-278893

**Comment by Chris-RH** [comment]
@ToolBar1024 

You can download your Asset Store invoices via your Asset Store account by following the steps below:

1. Sign in with your Unity ID at [assetstore.unity.com](https://assetstore.unity.com/).
2. Click your initials in the top right corner of the screen.
3. Click Order History (or Organization Orders) from the drop-down menu.
4. Click the invoice number next to the asset title to download the PDF.

If you cannot download your invoice, please contact Unity [Customer Experience team](https://support.unity.com/hc/en-us/requests/new?ticket_form_id=65905) and include the below information so that they can help you further:
The asset's name(s).
The email address used to purchase the asset.

**Comment by ToolBar1024** [comment]
@Chris-RH 
Hello ,I can't get the account's authorization,and I have decided to purchase it with the new account.
Can you tell me if we use this link https://assetstore.unity.com/packages/tools/video/avpro-video-v3-core-edition-278893 .

**Comment by ToolBar1024** [comment]
Hello, we have sent email to unitysupport@renderheads.com, Can you help me?
