### ISSUE TITLE
Failed iOS build from Unity: 2 duplicate symbols w/ IUnityGraphicsMetal_GUID

### ISSUE THREAD

**Issue by TheLampshady** [RenderHeads/UnityPlugin-AVProVideo#302]
Problem description:

We have the paid version and are receiving the following error when building in xcode from a Unity export. We have attempted this build on Unity v2019.3.0f6 -  v2019.3.5f1. Here is the 

```
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /build/iphone/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
duplicate symbol '_IUnityGraphicsMetalV1_GUID' in:
    ../app/build/iphone/Libraries/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalTextureDelegate.o)
../app/build/iphone/Libraries/Plugins/RenderHeads/AVProMovieCapture/Runtime/Plugins/iOS/libAVProMovieCapture.a(MCUnityPlugin.o)
duplicate symbol '_IUnityGraphicsMetal_GUID' in:
   ../app/build/iphone/Libraries/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalTextureDelegate.o)
 ../app/build/iphone/Libraries/Plugins/RenderHeads/AVProMovieCapture/Runtime/Plugins/iOS/libAVProMovieCapture.a(MCUnityPlugin.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Similar Issue:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/259

Device (which devices are you having the issue with - model, OS version number):
Error on build but iOS 13.x

System Information:

AVPro Video: plugin v1.10.1 scripts v1.10.1
Target Platform: iPhone
Unity: v2019.3.5f1 OSXEditor
OS: Desktop - MacBookPro13,3 - Mac OS X 10.15.3 - English
CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 8 threads - 16384KB
GPU: AMD Radeon Pro 450 - Apple - Metal - 2048KB - 16384

**Comment by AndrewRH** [comment]
Could you try upgrading to the latest version of the plugin (1.10.2) and try again?

Thanks,

**Comment by MorrisRH** [comment]
Those warnings are coming from the AVPro MovieCapture plugin and not AVPro Video. That being said they are just warnings and should not be causing the linker to fail.
Are you able to provide any more output from the build process?

**Comment by MorrisRH** [comment]
I've been unable to reproduce this using Unity2019.3.4f1 and the latest trial versions of both AVPro Video (1.10.2) and AVPro MovieCapture (4.1.0).

**Comment by TheLampshady** [comment]
Thank you for looking Andrew and Morris. I will upgrade to 1.10.2 shortly and reply with results. 

I receive an error for the build that prevents it from completing. The only other plugin I have in the Plugin/iOS folder is Firebase. Here is the command executed by xcode:

`
Ld /Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework normal arm64 (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /../app/builds/iphones
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios13.2 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/FirebaseCore -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/FirebaseCoreDiagnostics -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/FirebaseInstallations -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/FirebaseInstanceID -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/GoogleDataTransport -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/GoogleDataTransportCCTSupport -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/GoogleUtilities -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/PromisesObjC -L/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/nanopb -L/../app/builds/iphones/Libraries -L/../app/builds/iphones/Libraries/com.unity.xr.arkit/Runtime/iOS/Xcode1100 -L/../app/builds/iphones/Libraries/com.unity.xr.arkit-face-tracking/Runtime/iOS/Xcode1100 -L/../app/builds/iphones/Libraries/Plugins/iOS/Firebase -L/../app/builds/iphones/Libraries/Plugins/iOS -L/../app/builds/iphones/Libraries/Plugins/RenderHeads/AVProMovieCapture/Runtime/Plugins/iOS -F/Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos -F/../app/builds/iphones/Pods/Crashlytics/iOS -F/../app/builds/iphones/Pods/Fabric/iOS -F/../app/builds/iphones/Pods/FirebaseAnalytics/Frameworks -F/../app/builds/iphones/Pods/GoogleAppMeasurement/Frameworks -filelist /Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -ObjC -lFirebaseCore -lFirebaseCoreDiagnostics -lFirebaseInstallations -lFirebaseInstanceID -lGoogleDataTransport -lGoogleDataTransportCCTSupport -lGoogleUtilities -lPromisesObjC -lc++ -lnanopb -lsqlite3 -lz -framework CoreTelephony -framework Crashlytics -framework FIRAnalyticsConnector -framework Fabric -framework FirebaseAnalytics -framework Foundation -framework GoogleAppMeasurement -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp /../app/builds/iphones/Libraries/com.unity.xr.arkit/Runtime/iOS/Xcode1100/UnityARKit.a -lUnityARKitFaceTracking -lFirebaseCppCrashlytics -lCrashlyticsiOSWrapper -lAVProVideoiOS -lAVProMovieCapture -lFirebaseCppApp -framework ARKit -weak_framework Metal -weak_framework GameController -lPods-UnityFramework -lFirebaseCppAnalytics -Xlinker -dependency_info -Xlinker /Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/../Library/Developer/Xcode/DerivedData/Unity-iPhone-fmnfhgincdarzncvgvhyndhghnjb/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework
`

**Comment by TheLampshady** [comment]
Hello, I found some additional information. Whenever I add any other plugin to my project, AVPro produces the same error and the build fails.

I have attempted installing Firebase and Bugsnag separately . Both install to the "Plugins/iOS" folder and both cause the same error. All other packages from this folder fixes the build.

Let me know your thoughts! Thank you.

**Comment by MorrisRH** [comment]
The problem seems to be related to how you add the pods.
My Podfile contains two targets: Unity-iPhone and UnityFramework. Add the pods to Unity-iPhone and the build works fine, add them to UnityFramework and the build fails.
If you're able, can you move the pods to the target Unity-iPhone?

**Comment by DragontaleStudio** [comment]
I am having the same issue. @TheLampshady did the last suggestion (moving pods) fixed your error?

**Comment by TheLampshady** [comment]
Bugsnag does not have a Podfile (only Firebase) and building with Bugsnag (no podfile) has the same error. 

Does AVPro use a Podfile? If so, what does it look like and where does it live inside a Unity project.

**Comment by TheLampshady** [comment]
Hi @DragontaleStudio . It did not. I attempted to build in Unity, overwrite the Podfile from Firebase (deintegrating / cleaning) and building from xcode. 

Got a couple more errors looking like `Apple Mach-O Linker ..... _OBJC_CLASS_$_FIRConfiguration`

In the end, still have the pub symbol.

**Comment by MorrisRH** [comment]
No, we don't use Cocoapods with AVPro.

Bugsnag does make the issue show up though when linking in the trial version of AVPro Video (which also has duplicate symbols warnings normally).

Clearly something goes awry with the linker and the duplicate symbols are most likely the cause so we will endeavour to clear them.

**Comment by DragontaleStudio** [comment]
Just to clarify we are using paid and not trial version and we are currently blocked. Is there any update for resolution?

**Comment by MorrisRH** [comment]
AVPro Movie Capture 4.2.0 will be released very soon and no longer exposes those symbols.
Hopefully updating will solve the issue for you.

A version of AVPro Video with the symbols removed is still being worked on.

**Comment by MorrisRH** [comment]
AVPro Movie Capture 4.2.0 has been released. I'm hoping this resolves the issues you are having with linking.
Note: please delete the macOS plugin before updating, Unity's update system isn't able to upgrade it.

**Comment by aAAC** [comment]
@MorrisRH I've downloaded [water mark version of AVPro ](http://renderheads.com/products/avpro-video/) to test the adaptive streaming feature before purchasing the plugin.

Exporting the Xcode project from Unity gives the following errors:
Unity: 2019.3.9f1
Xcode: 11.4
AVPRo : 1.10.2 (updated on 20th March)

Error:

> ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/aali/Desktop/XCode_AMP_Branch/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
duplicate symbol '_IUnityGraphicsMetal_GUID' in:
    /Users/aali/Desktop/XCode_AMP_Branch/Libraries/MediaPlayer/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalWatermarkedTextureDelegate.o)
    /Users/aali/Desktop/XCode_AMP_Branch/Libraries/MediaPlayer/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalTextureDelegate.o)
duplicate symbol '_IUnityGraphicsMetalV1_GUID' in:
    /Users/aali/Desktop/XCode_AMP_Branch/Libraries/MediaPlayer/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalWatermarkedTextureDelegate.o)
    /Users/aali/Desktop/XCode_AMP_Branch/Libraries/MediaPlayer/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalTextureDelegate.o)
ld: 3 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you pls look into it quickly as we're kind of stuck atm.

**Comment by MorrisRH** [comment]
@aAAC We're looking to get a new build out as soon as possible, within the next day or so. I'll post here when it's available.

**Comment by MorrisRH** [comment]
1.10.3 has been released and should resolve this.

**Comment by TheLampshady** [comment]
@MorrisRH This works on our end. Thank you and team!
