### ISSUE TITLE
Over a hundred 'type or namespace not found' errors when upgrading from 1.0 to 2.0

### ISSUE THREAD

**Issue by bradleyKern** [RenderHeads/UnityPlugin-AVProVideo#615]
Hello. Today I tried to upgrade from the free trial of 1.0 to the Android version of 2.0.5.

My process was such:
1. Close Unity completely.
2. Reopen, and without doing anything else immediately import the unitypackage. 
3. After the import, I'm greeted with about 100 errors. Most of them are missing assembly errors.

Here's just a few:
`Assets\AVProVideo\Runtime\Scripts\AssetTypes\MediaReference.cs(15,10): error CS0246: The type or namespace name 'MediaPath' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\AVProVideo\Runtime\Scripts\AssetTypes\MediaReference.cs(20,10): error CS0246: The type or namespace name 'MediaHints' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\AVProVideo\Runtime\Scripts\Internal\Helper.cs(216,17): error CS0246: The type or namespace name 'TimeRange' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\AVProVideo\Runtime\Scripts\Components\MediaPlayer_PlatformOptions.cs(214,11): error CS0246: The type or namespace name 'Android' could not be found (are you missing a using directive or an assembly reference?)`

![image](https://user-images.githubusercontent.com/29763819/107057429-1088f380-6799-11eb-84a5-070bc693ad08.png)

**Comment by RenderHeadsSte** [comment]
Are you importing v2 over the top of a project already containing v1.x?  If so, this will not work.  We had to make a number of API changes for v2 that makes updating like this impossible. Instead you must only import v2 of AVPro Video into a project that does not contain version 1 asset files.

**Comment by RenderHeadsSte** [comment]
Does this help @bradleyKern?

**Comment by bradleyKern** [comment]
@RenderHeadsSte 

Thank you! That must have been it. I've got it going now. If it's not already mentioned in the documentation for the upgrade path, be sure to mention that those installing 2.0 should completely remove their 1.0 installation first.
